### ISSUE TITLE
CBL needs re-activation

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#1]

**Comment by sunt05** [comment]
1.  use `test-dev` as the base branch for the this work
2. read the code in `SUEWS-SourceCode/suews_ctrl_driver.f95`
3. modify the interface of `SUBROUTINE CBL(ifirst, Gridiv)` by adding arguments with explicit intents.
4. note the output are all handled by `SUEWS_update_output`: read the code in `SUEWS-SourceCode/suews_ctrl_output.f95`.

Please let me know if anything unclear: I'll modify/expand this post.

**Comment by sunt05** [comment]
@zhenkunl I put you here for role as "mentor" since you have better understanding of the current SUEWS code.

**Comment by zhenkunl** [comment]
I will assist Huang with the work

**Comment by zhenkunl** [comment]
I have checked out a new branch named `test-cbl` which is identical to `test-dev` at the moment. @HUANGWJ11 You can git clone this repo to start to work.

**Comment by HUANGWJ11** [comment]
![CBLinput](https://user-images.githubusercontent.com/54320522/63659083-da90c300-c7e1-11e9-91cd-38ed91a2a963.png)
This is the CBL input and calculation process

**Comment by sunt05** [comment]
@HUANGWJ11 the flowchart is great!
it would also be good to summarise the input and output variables here before you put hands onto the code.
