### ISSUE TITLE
Missing recent publications

### ISSUE THREAD

**Issue by suegrimmond** [Urban-Meteorology-Reading/SUEWS#100]
**Describe the bug**
Missing
Leena's CO2 paper
SuPy Paper
Tom's latest paper
Ao's paper

**Location**
https://suews-docs.readthedocs.io/en/latest/recent-publications.html

**Expected statement**
 Is there some 'smart' way  we can capture these automatically going forward?

But at least need to manually update the development publications

**Screenshots**

**Additional context**

**Comment by sunt05** [comment]
resolved in https://github.com/Urban-Meteorology-Reading/SUEWS/pull/101/commits/c31e55acf55b5c416b8dbc47fd3fa823b5dd8711.

**Comment by suegrimmond** [comment]
It doesn't quite finish with the link to the papers at "recent" link

**Comment by sunt05** [comment]
Then shall we rename it to *selected SUEWS papers*? Or how *recent* should we include the papers?

**Comment by suegrimmond** [comment]
Do you think your fix has changed this? I.e. what is seen at that page/link?

**Comment by sunt05** [comment]
now resolved: but need to get the order more *recent* as discussed.

**Comment by sunt05** [comment]
also fixed the reversed chronological order.
