### ISSUE TITLE
malformatted output files by v2019a

### ISSUE THREAD

**Issue by ljarvi** [Urban-Meteorology-Reading/SUEWS#107]
When the output files generated by SUEWS_V2019a are opened in excel some of the punctuation marks are dots and some comma's. I'm not sure why this is but it would be easier for certain users if the output files would save data in such format that also is easily read by spreadsheets.

**Comment by sunt05** [comment]
can you provide an example please?

**Comment by ljarvi** [comment]
Please find an example enclosed.

Leena

--
Leena Järvi (PhD, docent)
Associate Professor in Applied Urban Meteorology
Institute for Atmospheric and Earth System Research (INAR) / Physics &
Helsinki Institute of Sustainability Science (HELSUS)
Faculty of Science
University of Helsinki
Tel: +358 503110371

**Comment by sunt05** [comment]
can you post an example file please? what I received is pure text and hard to debug.
Also, please point out where the issue is (e.g., which line the problem is spotted).
