### ISSUE TITLE
improve the computational performance of RSL

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#113]
The computational performance of RSL is critical as near surface diagnostics are all produced by it; these diagnostics should potentially be used in iterations of each tilmestep as forcing representing the local context.

**Comment by sunt05** [comment]
@natalieth would the analytical forms used in the ref below be useful for this?

> Arnqvist, J. and Bergström, H.: Flux‐profile relation with roughness sublayer correction, Q J Roy Meteor Soc, 141(689), 1191–1197, doi:10.1002/qj.2426, 2014.

**Comment by rarygit** [comment]
I found Xuelong Chen's recent study on roughness sublayer length to be quite illuminating and comprehensive.
He presents a methodical approach in deriving the model parameterisation. 

Chen, X., Massman, W. J., & Su, Z. (2019). A column canopy‐air turbulent diffusion method for different canopy structures. Journal of Geophysical Research: Atmospheres, 124, 488–506. https://doi.org/10.1029/2018JD028883

You have probably already seen Giometto's study and associated simulations (videos).
"Spatial Characteristics of Roughness Sublayer Mean Flow and Turbulence Over a Realistic Urban Surface"
https://link.springer.com/article/10.1007/s10546-016-0157-6
