### ISSUE TITLE
SUEWS prepare doesn't run

### ISSUE THREAD

**Issue by Fermiotis** [Urban-Meteorology-Reading/SUEWS#120]
**Describe the bug**
i prepare all the inputs and then use SUEWS prepare plugin and don work

**To Reproduce**
[mediumlarge.zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/4707792/mediumlarge.zip)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/61833032/83355271-0ccde300-a367-11ea-960a-36cedfc78c80.png)

**Version and platform (please complete the following information):**
- SUEWS version: 3.13.1
- OS: Windows 10

**Additional context**

**Comment by sunt05** [comment]
similar to #121. Please raise this issue in the [UMEP repo](https://github.com/UMEP-dev/UMEP/issues).
