### ISSUE TITLE
SUEWS advanced doesn't start

### ISSUE THREAD

**Issue by Fermiotis** [Urban-Meteorology-Reading/SUEWS#121]
**Describe the bug**
trying to run the model and doesn't start with this error in the screen, also tried to update the supy but after the update also didn't work.
[hersmall.zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/4707910/hersmall.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/61833032/83356640-1c055e80-a370-11ea-9a99-f0d3da1f3776.png)

**Version and platform (please complete the following information):**
- SUEWS version: 3.13.1
- Windows 10

**Additional context**

**Comment by sunt05** [comment]
This is not an issue related to SUEWS model but to UMEP. Please raise this issue [there](https://github.com/UMEP-dev/UMEP/issues).
