### ISSUE TITLE
possible corner case for inappropriate height of roughness elements

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#127]
say `sfr_bldg=0.0001` and buildings are the only tall roughness element (i.e., no trees) in a given grid, the approach below would estimate the effective height of roughness elements as the building height however the coverage is minimal, which might be unrealistic.

https://github.com/Urban-Meteorology-Reading/SUEWS/blob/9bad32aa5ea4ffb13090d763938737421b071680/SUEWS-SourceCode/suews_phys_resist.f95#L464-L465

**Comment by sunt05** [comment]
discussed this with Sue: `Zh` should be kept as is, `planF` should be corrected by removing the denominator part (i.e., without normalisation by `zreaZh`).

**Comment by suegrimmond** [comment]
not -dot+product
