### ISSUE TITLE
Problem with T2

### ISSUE THREAD

**Issue by Empanag** [Urban-Meteorology-Reading/SUEWS#132]
**Describe the bug**
I m trying to run the SUEWS simple model and the results seems wrong also different from older run test with the same inputs

**To Reproduce**
[input2.zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/5157081/input2.zip)
and the settings
![image](https://user-images.githubusercontent.com/61833032/91868161-1d02a080-ec7d-11ea-88f8-206091ffc578.png)

**Expected behavior**
in the diagram you can see the run that i had tested on may that is close to the input data of air tmp as expected but the new run that i did today is very different from the last as you can see with gray color 

**Screenshots**
![image](https://user-images.githubusercontent.com/61833032/91868360-563b1080-ec7d-11ea-99c8-36ea4b1d0c1c.png)

**Version and platform (please complete the following information):**
- SUEWS version: 3.15.3 
- OS: Windows 10

**Additional context**

**Comment by sunt05** [comment]
Hi @Empanag, I'll look into this issue soon.

**Comment by sunt05** [comment]
hi @Empanag, 
As you input data are not ideal for me to test straightforward, I just gathered as much info as I can to do a supy (ver: 2020.8.9) run here, the results of which are quite different from what you posted above:
![download](https://user-images.githubusercontent.com/1802656/92104472-48020700-edd9-11ea-9209-992ca4f36ed5.png)


Also, the version info you reported is not for SUEWS but (I guess) for QGIS-UMEP; please check the SuPy version as follows in the python console of QGIS:
```
import supy as sp
sp.show_version()
``
which should give a bunch of info about versions of suey-related packages.
please post those here for my debugging.
thanks!

**Comment by Empanag** [comment]
I have this version

supy: 2020.6.30 
supy_driver: 2020b1

**Comment by sunt05** [comment]
please update to the latest supy; the version you are using is known to have some issues.

**Comment by Empanag** [comment]
Okey seems that works. Is there any way to change the albedo in simple model or emissivity?

**Comment by sunt05** [comment]
Good to know the issue has been resolved. 
Regarding changing things in your so-called “simple model”, I think that can only be addressed at the UMEP side. 
Or, you need to use the advanced mode of SUEWS in UMEP.
