### ISSUE TITLE
[Docs]input_files/SUEWS_SiteInfo/SUEWS_SiteSelect

### ISSUE THREAD

**Issue by biglimp** [Urban-Meteorology-Reading/SUEWS#136]
[source doc](https://github.com/Urban-Meteorology-Reading/SUEWS/blob/master/docs/source/input_files/SUEWS_SiteInfo/SUEWS_SiteSelect.rst)
[rtd page](https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/SUEWS_SiteSelect.html)

The numbering is wrong

**Comment by sunt05** [comment]
some columns are missing.
