### ISSUE TITLE
Input hourly irrigation data are not reflected in SUEWS output in UMEP 3.15.4, QGIS 3.16

### ISSUE THREAD

**Issue by cpk105** [Urban-Meteorology-Reading/SUEWS#137]
**Describe the bug**
I used the UMEP plugin in QGIS 3.16 to run SUEWS. I have included hourly irrigation data (a fixed 5 L/hr for the first 17 days and 0 L/hr for the rest) in the "External water use [Wuh]" column in the meteorological input file (https://suews-docs.readthedocs.io/en/latest/input_files/met_input.html?highlight=external#ssss-yyyy-data-tt-txt) and successfully run the model. However, the "Irrigation [Irr]" column in the SUEWS output files did not show any irrigation, i.e. 0 mm.

**To Reproduce**
Input files:
[SUEWS prepare (input).zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/5504564/SUEWS.prepare.input.zip)
Output files:
[SUEWS output.zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/5504565/SUEWS.output.zip)
SuPy (It seems that the information about the run that produced the above output file is not shown in SuPy):
[SuPy.log](https://github.com/Urban-Meteorology-Reading/SUEWS/files/5504567/SuPy.log)

**Expected behavior**
The "Irrigation [Irr]" column in the SUEWS output files should show non-zero irrigation.

**Screenshots**
![image](https://user-images.githubusercontent.com/54835679/98438624-bc418980-213f-11eb-8cdc-8bd0be83b347.png)

**Version and platform (please complete the following information):**
- SUEWS version: Not sure.
- UMEP 3.15.4
- QGIS 3.16
- OS: Windows 10

**Additional context**
None.

Thank you.

**Comment by sunt05** [comment]
Did you set the irrigation to be externally forced?
Please check this option:
https://suews.readthedocs.io/en/latest/input_files/RunControl/scheme_options.html#cmdoption-arg-WaterUseMethod

**Comment by cpk105** [comment]
Oh right I haven't set irrigation to be externally forced. Now I can see that the irrigation data are reflected in the SUEWS output.

I would be very grateful if you can help me with the following two questions as well:
1. How can I apply different irrigation data to different grids?
2. How can I control how the applied irrigation, e.g. 10 mm, is distributed over different surfaces within a grid (e.g. 6 mm for grass and 3 mm for deciduous trees and 1 mm for paved surface)?

Thank you very much!

**Comment by cpk105** [comment]
One more question:
3. The unit of "External water use [Wuh]" is m^3 (https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/Input_Options.html#cmdoption-arg-Wuh), but my irrigation data are in mm. Does that mean that I have to know the area of the irrigated surface to convert irrigation rate in mm to m^3?

**Comment by sunt05** [comment]
> 1. How can I apply different irrigation data to different grids?

you need to different prepare forcing data for different grids.

> 2. How can I control how the applied irrigation, e.g. 10 mm, is distributed over different surfaces within a grid (e.g. 6 mm for grass and 3 mm for deciduous trees and 1 mm for paved surface)?

please specify the columns starting with `IrrFr_` for different land covers.
https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/Input_Options.html#cmdoption-arg-IrrFr_Paved

**Comment by sunt05** [comment]
> 3. The unit of "External water use [Wuh]" is m^3 (https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/Input_Options.html#cmdoption-arg-Wuh), but my irrigation data are in mm. Does that mean that I have to know the area of the irrigated surface to convert irrigation rate in mm to m^3?

Yes, input data have to be converted to proper units by considering the surface area as specified in [`SurfaceArea`](https://suews.readthedocs.io/en/latest/input_files/SUEWS_SiteInfo/Input_Options.html#cmdoption-arg-SurfaceArea).

**Comment by cpk105** [comment]
@sunt05 Thank you very much for your prompt reply. I will explore your suggestions and get back to this issue later.

**Comment by cpk105** [comment]
1. I'm wondering how can I use different forcing data for different grids? I have looked at the manual page (https://suews-docs.readthedocs.io/en/latest/prepare-to-run-the-model.html?highlight=downscale#preparation-of-the-meteorological-forcing-data) but I can't find the details.

2. This manual page also says that downscaling of the timescale of the forcing data is possible? How can I downscale the forcing data from 60 min to 5 min in UMEP?

Thank you very much.

**Comment by sunt05** [comment]
> 1. I'm wondering how can I use different forcing data for different grids? I have looked at the manual page (https://suews-docs.readthedocs.io/en/latest/prepare-to-run-the-model.html?highlight=downscale#preparation-of-the-meteorological-forcing-data) but I can't find the details.

Please use this option:
 
https://suews-docs.readthedocs.io/en/latest/input_files/RunControl/File_related_options.html#cmdoption-arg-MultipleMetFiles

and see here:

https://suews-docs.readthedocs.io/en/latest/input_files/met_input.html


> 2. This manual page also says that downscaling of the timescale of the forcing data is possible? How can I downscale the forcing data from 60 min to 5 min in UMEP?

Please see here:
https://suews-docs.readthedocs.io/en/latest/input_files/RunControl/Time_related_options.html#cmdoption-arg-ResolutionFilesIn

> 
> Thank you very much.

**Comment by cpk105** [comment]
Thank you. I'm using UMEP to generate a set of files from "SUEWS prepare" and use this set of files as the input files for "SUEWS advanced". This set of files from "SUEWS prepare" does not contain "RunControl.nml" and therefore I'm unable to change the **MultipleMetFiles** and **ResolutionFilesIn** parameters.

The files that I got from "SUEWS prepare" are attached here:
[SUEWS prepare.zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/5578696/SUEWS.prepare.zip)

However, if "SUEWS advanced" has run successfully, "RunControl.nml" would appear in the output folder:
[SUEWS output.zip](https://github.com/Urban-Meteorology-Reading/SUEWS/files/5578703/SUEWS.output.zip)
