### ISSUE TITLE
Aggregate output to Surfaces or to Polygons of Interest ("POLOI")

### ISSUE THREAD

**Issue by rarygit** [Urban-Meteorology-Reading/SUEWS#138]
**Is your feature request related to a problem? 
In some circumstances, output data aggregated at the level of the grid is either too coarse or misses important information at the sub-grid level.
For example sensible heat fluxes, latent energy fluxes, surface runoff.  
Furthermore, SOLWEIG Tmrt values (subcanopy) can be influenced by soil moisture levels (e.g. irrigation, surface runon routed from impermeable surfaces). Maybe this aspect is a separate, but related, issue.

**Describe the solution you'd like**
Aggregate output data at the level of surfaces (i.e. buildings, paving, vegetation canopy) or/and "polygons of interest" POLOI rather than just POI). 

**Describe alternatives you've considered**
Start with changes to fortran file "suews_ctrl_output.f95"
Are there individual/s who is/are able to volunteer/mentor/assist with alterations to the source for such a purpose?
I say "volunteer" in relation to zero funding for the programming hours involved.   

**Additional context**
N/A

**Comment by sunt05** [comment]
Thanks for the suggestion.
I feel such post-processing functionalities can better be implemented within `SuPy` or other GIS-focused framework.

However, I'll leave this open for a while and see if other interests/ideas can appear within the SUEWS community.

**Comment by rarygit** [comment]
Thanks for the quick reply!

Post-processing with python/qgis framework is a good suggestion.

I hope this request is enough to trigger interest.
