### ISSUE TITLE
simplify `siteselect`

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#142]
1. principle to be set up for this "master" table:
- only meta info of grid should be included as explicit values ; e.g., name, coordinates, altitude, land cover fraction
- other specific properties should be only included as reference code to respective property tables; e.g., `SUEWS_Veg.txt`

2. legacy stuffs to be removed:

-  e.g., LUMPS related parameters

**Comment by suegrimmond** [comment]
legacy to be moved to legacy - only remove if no longer used
