### ISSUE TITLE
incorporation of RSL wind profile 

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#22]
Hi @natalieth, I just read through your code and would suggest replace the `avU10_ms`, 10 m agl wind speed, produced as a diagnostic by `SUEWS_cal_Diagnostics` with your `u(z)` at `z=10+z0m`:
https://github.com/Urban-Meteorology-Reading/SUEWS/blob/eef66015af1d791ce55e96fac668d2795c60aaac/SUEWS-SourceCode/suews_ctrl_driver.f95#L723-L729

How do you think?

**Comment by natalieth** [comment]
Quick update: 
Have now updated the RSL-subroutine to incorporate temperature and specific humidity profiles as well as wind speed. These are just part of one array for now: 30 wind speed levels, 30 Temperature levels, and 30 specific humidity levels.
Will add to the documentation.

**Comment by sunt05** [comment]
need a plot showing the validity of this scheme.

**Comment by sunt05** [comment]
@natalieth I've sent you a separate email for observation to evaluate this module. I put it here as reminder for the unresolved task.
