### ISSUE TITLE
RSL profiles if zh is small

### ISSUE THREAD

**Issue by natalieth** [Urban-Meteorology-Reading/SUEWS#24]
RSL profiles are not dependent on zh (combined tree and building canopy height):

`dz = Zh/10.`
`zarray = (/(I, I=1, nz)/)*dz`

But if the canopy height is small the heights are all very close to the surface and the entire U-profile will be 0's/NaN's. Alternatively, we can used fixed heights over which to calculate a profile.

**Comment by sunt05** [comment]
The 30 levels start at 0.1 zh and end 3.0 zh; so the in & out ranges of zh can be covered.
