### ISSUE TITLE
add Doxygen and sphinx support

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#30]
- [x] add Doxygen support
- [x] add `exhale` support for sphinx
- [x] generate call-graphs

~~- [ ] enrich the documentation of major components in the `driver` subroutine~~

**Comment by sunt05** [comment]
@hamidrezaomidvar let's use `2019a-dev` branch for this work.

**Comment by sunt05** [comment]
@hamidrezaomidvar have you started working on this? 
If not, I'm about to move forward: I just sorted out various other merging related to the `2019a-dev` branch and we can use `test-dev` now for the incorporation, which has some tests set up to ensure better the branch quality.
If you've started, I'll just hold and we can have a chat for moving forward.

**Comment by hamidrezaomidvar** [comment]
@sunt05 I am learning about doxygen right now, so I have not created a branch. So should I use test-dev for this?

**Comment by sunt05** [comment]
Yes, let's use `test-dev` branch for this from now on.

**Comment by sunt05** [comment]
@hamidrezaomidvar 
I Have read this a while ago when learning Doxygen for fortran:
https://modelingguru.nasa.gov/docs/DOC-1811
See if this is would be useful.

**Comment by hamidrezaomidvar** [comment]
Thanks! That's what I have been looking at. It is useful.

**Comment by hamidrezaomidvar** [comment]
@sunt05 I added a folder called docs_Doxygen that contains the Doxygen configuration and other files. It uses SUEWS source codes files to generate the documentation. I added a main page as introduction using the current introduction from the docs. Now we can start the documentation of the source code files starting with driver

**Comment by hamidrezaomidvar** [comment]
@sunt05 Just pushed the latest version

**Comment by sunt05** [comment]
Finally got this working!
https://suews-docs.readthedocs.io/en/test-dev/api.html

**Comment by sunt05** [comment]
Now we need to plan the documentation of code.
Also, one thing to notice for the future build:
`exhale` can be very consuming so RTD server will hang up then fail the builds.

So we still need to consider a proper way to integrate some of the code documentation into Sphinx.

But anyway, we can start documenting the code: at least we got a working version on RTD.

**Comment by suegrimmond** [comment]
Very nice!!

Best wishes
Sue
============================================
Prof Sue Grimmond
Dept. of Meteorology, University of Reading, Reading, RG6 6BB
T: 44 118 378 6248 – messages get emailed to me
O:Met Building (#58 on map) rm:1U14
E: c.s.grimmond@reading.ac.uk<mailto:c.s.grimmond@reading.ac.uk>
W: http://micromet.reading.ac.uk/
