### ISSUE TITLE
cbl suews v2017b

### ISSUE THREAD

**Issue by parisakhj** [Urban-Meteorology-Reading/SUEWS#34]
[SUEWS_FILES.zip](https://github.com/Urban-Meteorology-Reading/SUEWS-Docs/files/3364993/SUEWS_FILES.zip)

**Describe the Issue**
Hello;
I made txt and nml files for the boundary layer. But when I run the model, I get an error. Can you help me find out where is the problem? I saved all these files to the desktop directory. I'm using version 2017b.

**Location**

**Screenshots**
![cblinputnml](https://user-images.githubusercontent.com/44317709/60743525-49dafb00-9f87-11e9-99fc-052a1e60e070.PNG)
![initialdata](https://user-images.githubusercontent.com/44317709/60743530-51020900-9f87-11e9-8358-bcef45645bbd.PNG)
![error](https://user-images.githubusercontent.com/44317709/60743547-6414d900-9f87-11e9-8f68-e9acf95ff0df.PNG)

**Additional context**

**Comment by sunt05** [comment]
No response from the OP for a while.
Closed it.
