### ISSUE TITLE
Documentation for RSL wind profiles

### ISSUE THREAD

**Issue by natalieth** [Urban-Meteorology-Reading/SUEWS#35]
*At the moment this is default in 'test_dev_RSL'-branch but should be added as an option. Will update when model is further developed*

**Wind profiles in the roughness sublayer**
Wind profiles are derived at 30 levels in the surface layer. In order to account for the roughness sublayer and canopy layer, we follow Harman and Finnigan (2007) and Theeuwes et al. (2019). 
The 30 levels have a step of 0.1 times the canopy height (*should still output zh somewhere*) `dz = 0.1 * zh`. However. if 3 x canopy height is less the 10 m steps of 0.3333 m are used:
` IF ((3.*Zh) < 10.) THEN`
`     dz = 1./3.   `  
`     zarray = (/(I, I=1, nz)/)*dz...`
Here nz is 30. 

The results are written to ..._RSL_60.txt, where U_1 ... U_30 are the the wind speed calculated at 0.1Zh ... 3.0Zh. 

References:
Harman IN, Finnigan JJ (2007) A simple unied theory for flow in the canopy and roughness sublayer. Boundary-Layer Meteorol 123(2):339--363
Theeuwes NE, Ronda RJ, Harman IN, Christen A, Grimmond CSB (2019) Parametrizing Horizontally Averaged Wind and Temperature Profiles in the Urban Roughness Sublayer. Boundary-Layer Meteorol *accepted*

**Comment by sunt05** [comment]
@natalieth following the code completion in #22 , please add your documentation here.
I'll incorporate your text to the docs files as we are improving the documentation workflow at moment. So please avoid editing the docs file directly. Thanks!

**Comment by natalieth** [comment]
*UPDATE:: At the moment this is default in 'test_dev_RSL'-branch but should be added as an option. Will update when model is further developed*

**Wind, temperature and humidity profiles in the roughness sublayer**
Wind, temperature and humidity profiles are derived at 30 levels in the surface layer. In order to account for the roughness sublayer and canopy layer, we follow Harman and Finnigan (2007), Harman and Finnigan 2008, and Theeuwes et al. (2019). 
The 30 levels have a step of 0.1 times the canopy height (*should still output zh somewhere*) `dz = 0.1 * zh`. However. if 3 x canopy height is less the 10 m steps of 0.3333 m are used:
` IF ((3.*Zh) < 10.) THEN`
`     dz = 1./3.   `  
`     zarray = (/(I, I=1, nz)/)*dz...`
Here nz = 30. 

The results are written to ..._RSL_60.txt, in 90 columns, where U_1 ... U_30, are the the wind speed calculated at 0.1Zh ... 3.0Zh, T_1 ... T_30, are the the temperature (degC) calculated at 0.1Zh ... 3.0Zh, and q_1 ... q_30, are the the specific humidity (g kg) calculated at 0.1Zh ... 3.0Zh.

References:
Harman IN, Finnigan JJ (2007) A simple unied theory for flow in the canopy and roughness sublayer. Boundary-Layer Meteorol 123(2):339--363
Harman, IN, Finnigan, JJ (2008) Scalar concentration profiles in the canopy and roughness sublayer. Boundary-layer meteorol, 129(3), 323--351.
Theeuwes NE, Ronda RJ, Harman IN, Christen A, Grimmond CSB (2019) Parametrizing Horizontally Averaged Wind and Temperature Profiles in the Urban Roughness Sublayer. Boundary-Layer Meteorol *accepted*

**Comment by sunt05** [comment]
added in https://github.com/Urban-Meteorology-Reading/SUEWS/commit/05b033d73ecb3c5a233e26ef4f9083e5be43828c
