### ISSUE TITLE
improve coding guidelines

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#36]
**Describe the Issue**
The coding (documenting) guidelines for SUEWS should be improved to reflect the new features and practises in the recent and near future development.

**Location**
~~https://suews-docs.readthedocs.io/en/latest/development.html~~
updated one:
https://suews.readthedocs.io/en/latest/development/development.html

**Comment by sunt05** [comment]
@zhenkunl @hamidrezaomidvar please have a look at the above page.
Then contribute your thoughts here: how can we make the guidelines useful for SUEWS developers?
Thanks!

**Comment by hamidrezaomidvar** [comment]
The above page does not show for me. I think it is moved?

**Comment by sunt05** [comment]
Sorry, here is the updated link:
https://suews.readthedocs.io/en/latest/development/development.html

**Comment by suegrimmond** [comment]
SUEWS/docs/source/development/coding_guideline.rst


10.1. Coding Guidelines
10.1.1. Coding
... Code is hosted in GitHub as **private repository.** Variables. ...
-Does this needs to be updated?

**Comment by sunt05** [comment]
Yes, definitely.
And as we are releasing it to the public for external contributions, the whole section might need an overhaul.
