### ISSUE TITLE
Errors in stability functions for heat

### ISSUE THREAD

**Issue by natalieth** [Urban-Meteorology-Reading/SUEWS#39]
There seems to be an error in the stability function for heat (PSI_H):
https://github.com/Urban-Meteorology-Reading/SUEWS/blob/94cb47f655d2ffcd5a4277119dd7cb0253240da5/SUEWS-SourceCode/suews_phys_atmmoiststab.f95#L415
This should be:
`PSYH = 2*LOG((1 + x)/2)`
otherwise the unstable z/L's become stable.

and 
https://github.com/Urban-Meteorology-Reading/SUEWS/blob/94cb47f655d2ffcd5a4277119dd7cb0253240da5/SUEWS-SourceCode/suews_phys_atmmoiststab.f95#L409
should be:
`x = 0.95*(1.-11.6*zl_f)**(0.5)` 

I have updated this in the test-dev-RSL branch

**Comment by sunt05** [comment]
Thanks for the correction.
Please double-check if the reference associated with the formulation is correct; if not, please provide a reference to the correct formulation as well.
