### ISSUE TITLE
add a plot for different stability correction schemes

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#45]
To examine the validity of implemented schemes.

related: #39

**Comment by sunt05** [comment]
## Source code of the Psi functions implemented in SUEWS:

### momentum
https://github.com/Urban-Meteorology-Reading/SUEWS/blob/ac9ca1b7419871fa38a3ebf2b56976e8a555d80e/SUEWS-SourceCode/suews_phys_atmmoiststab.f95#L247-L325

### heat
https://github.com/Urban-Meteorology-Reading/SUEWS/blob/ac9ca1b7419871fa38a3ebf2b56976e8a555d80e/SUEWS-SourceCode/suews_phys_atmmoiststab.f95#L388-L438

**Comment by sunt05** [comment]
@matthew0512l 
here are some example plots:

![image](https://user-images.githubusercontent.com/1802656/62533101-ca6a7100-b83d-11e9-9c6f-2176fe116d9a.png)

![image](https://user-images.githubusercontent.com/1802656/62533042-a9a21b80-b83d-11e9-9439-8360f3c0b952.png)

**Comment by matthew0512l** [comment]
![psyh_stab_corr_func](https://user-images.githubusercontent.com/48319587/62621309-7631c080-b913-11e9-9b9c-c5c5f09769b9.png)
![psym_stab_corr_func](https://user-images.githubusercontent.com/48319587/62621310-76ca5700-b913-11e9-91e5-28444831e3f1.png)

above is momentum, below is heat

**Comment by sunt05** [comment]
great!
would be good to use some symbols for more apparent representations.

**Comment by sunt05** [comment]
can you also post the code here?

**Comment by matthew0512l** [comment]
`"""
Created on Tue Aug  6 15:15:46 2019

"""

import numpy as np
import matplotlib.pyplot as plt


neut_limit = 0.001 # constant: neutral limit of z/L
piover2 = np.pi/2

#methods (checked 07/08/19)

#momentum
# - unstable
def method_u1m(zl_f):
    
    '''
    psym = ((1.-16.*zl_f)**0.25) - 1
    '''
    
    psym = ((1.-16.*zl_f)**0.25) - 1
    
    return psym

def method_u2m(zl_f):
    
    '''
    X = (1.-(15.2*zl_f))**0.25
    X2 = LOG((1 + (X**2.))/2.)
    PSYM = (2.*LOG((1 + X)/2.)) + X2 - (2.*ATAN(X)) + PIOVER2
    '''
    
    x = (1.-(15.2*zl_f))**0.25
    x2 = np.log((1 + (x**2.))/2.)
    psym = (2.*np.log((1 + x)/2.)) + x2 - (2.*np.arctan(x)) + piover2
    
    return psym

def method_u3m(zl_f):
    
    '''
    psym = 0.6*(2)*LOG((1 + (1 - 16*zl_f)**0.5)/2)
    '''
    
    psym = 0.6*(2)*np.log((1 + (1 - 16*zl_f)**0.5)/2)
    
    return psym

def method_u4m(zl_f):
    
    '''
    x = (1 - 19.3*zl_f)**(-0.25)
    X2 = LOG((1 + (X**2.))/2.)
    PSYM = (2.*LOG((1 + X)/2.)) + X2 - (2.*ATAN(X)) + PIOVER2
    '''
    
    x = (1 - 19.3*zl_f)**(-0.25)
    x2 = np.log((1 + (x**2.))/2.)
    psym = (2.*np.log((1 + x)/2.)) + x2 - (2.*np.arctan(x)) + piover2
    
    return psym

def method_u5m(zl_f):
    
    '''
    IF (zl_f >= -0.16) THEN
        x = 1 + 1.38*zl_f
    ELSE
        x = 0.42*(-1)*zl_f**0.333
    ENDIF
    X2 = LOG((1 + (X**2.))/2.)
    PSYM = (2.*LOG((1 + X)/2.)) + X2 - (2.*ATAN(X)) + PIOVER2
    '''
    
    zl_fl = zl_f[zl_f >= -0.16]
    zl_fs = zl_f[zl_f < -0.16]
    
    xl = 1 + 1.38*zl_fl

    xs = 0.42*(-zl_fs)**0.333
    
    x = np.concatenate((xs,xl))

    x2 = np.log((1 + (x**2.))/2.)
    psym = (2.*np.log((1 + x)/2.)) + x2 - (2.*np.arctan(x)) + piover2
    
    return psym

def method_u6m(zl_f):
    
    '''
    IF (zl_f >= 0.06) THEN
        x = 1
    ELSE
        x = ((-1)*zl_f/0.06)**0.25
    ENDIF
    X2 = LOG((1 + (X**2.))/2.)
    PSYM = (2.*LOG((1 + X)/2.)) + X2 - (2.*ATAN(X)) + PIOVER2
    '''
    
    x = ((-1)*zl_f/0.06)**0.25
    
    x2 = np.log((1 + (x**2.))/2.)
    
    psym = (2.*np.log((1 + x)/2.)) + x2 - (2.*np.arctan(x)) + piover2
    
    return psym

def method_u7m(zl_f):
    
    '''
    X = (1 - (28.*zl_f))**0.25  ! NT: changed + to - (bug -> checked reference)
    X2 = LOG((1 + X**2.)/2.)
    PSYM = (2.*LOG((1 + X)/2.)) + X2 - (2.*ATAN(X)) + PIOVER2
    '''
    
    x = (1 - (28.*zl_f))**0.25  #! NT: changed + to - (bug -> checked reference)
    x2 = np.log((1 + x**2.)/2.)
    psym = (2.*np.log((1 + x)/2.)) + x2 - (2.*np.arctan(x)) + piover2
    
    return psym

# - stable
def method_s1m(zl_f):
    
    '''
    psym = (-4.8)*zl_f
    '''
    psym = (-4.8)*zl_f
    
    return psym

def method_s2m(zl_f):
    
    '''
    IF (zl_f > 1000.) THEN
        zl_f = 1000.
    END IF
    PSYM = (-17.*(1.-EXP(-0.29*zl_f)))
    '''
    
    psym = (-17.*(1.-np.exp(-0.29*zl_f)))
    
    return psym

def method_s3m(zl_f):
    
    '''
    psym = (-6)*LOG(1 + zl_f)
    '''
    psym = (-6)*np.log(1 + zl_f)
    
    return psym

def method_s4m(zl_f):
    
    '''
    ! psym=1+6*zl_f  ! this is NOT the integral form but the stability function, TS 13 Jun 2017
    psym = (-6)*zl_f   ! this is the integral form, TS 13 Jun 2017
    '''
    
    psym=(-6)*zl_f
    
    return psym

#------------------------------------------------------------------------------
#heat
# - unstable
def method_u2h(zl_f):
    
    '''
    x = 0.95*(1.-15.2*zl_f)**0.5 
    PSYH = 2*LOG((1 + x)/2) 
    '''
    x = 0.95*(1.-15.2*zl_f)**0.5 
    psyh = 2*np.log((1 + x)/2) 
    
    return psyh

def method_u3h(zl_f):
    
    '''
    psyh = 0.6*(2)*LOG((1 + (1 - 16*zl_f)**0.5)/2) 
    '''
    
    psyh = 0.6*(2)*np.log((1 + (1 - 16*zl_f)**0.5)/2) 
    
    return psyh

def method_u4h(zl_f):
    
    '''
    x = 0.95*(1.-11.6*zl_f)**(0.5) 
    PSYH = 2*LOG((1 + x)/2) 
    '''
    x = 0.95*(1.-11.6*zl_f)**(0.5) 
    psyh = 2*np.log((1 + x)/2)
    
    return psyh

def method_u7h(zl_f):
    
    '''
    x = (1 - (28.*ZL))**0.25 
    PSYH = 2*LOG((1 + x)/2) 
    '''
    
    x = (1 - (28.*zl_f))**0.25 
    psyh = 2*np.log((1 + x)/2) 
    
    return psyh

# - stable
def method_s4h(zl_f):
    
    '''
    IF (zL <= 1) THEN ! weak/moderate stable 
          IF (StabilityMethod == 4) THEN !Businger et al (1971) modifed  Hogstrom (1988) 
             psyh = (-7.8)*zl_f   
             
    ELSE  
          ! adopt the form as Brutasert (1982) eqn 4.58. but following the coeffs. of the above eqns 
          IF (StabilityMethod == 4) THEN !Businger et al (1971) modifed  Hogstrom (1988) 
             psyh = (-7.8)*(1 + LOG(zl_f))
    '''
    
    zl_fl = zl_f[zl_f > 1]
    zl_fs = zl_f[zl_f <= 1]
    
    psyh_l = (-7.8)*(1 + np.log(zl_fl))
    psyh_s = (-7.8)*zl_fs
    
    psyh = np.concatenate((psyh_s,psyh_l))
    
    return psyh

def method_sdyerh(zl_f):
    
    '''
    IF (zL <= 1) THEN ! weak/moderate stable 
          ELSE !Dyer (1974)  PSYH=(-5)*ZL        modifed  Hogstrom (1988) 
             PSYH = (-4.5)*Zl_f   
             
    ELSE  
          ! adopt the form as Brutasert (1982) eqn 4.58. but following the coeffs. of the above eqns 
          ELSE !Dyer (1974)  PSYH=(-5)*ZL        modifed  Hogstrom (1988) 
             PSYH = (-4.5)*(1 + LOG(zl_f)) 
    '''
    
    zl_fl = zl_f[zl_f > 1]
    zl_fs = zl_f[zl_f <= 1]
    
    psyh_l = (-4.5)*(1 + np.log(zl_fl))  
    psyh_s = (-4.5)*zl_fs  
    
    psyh = np.concatenate((psyh_s,psyh_l))
    
    return psyh
     
#------------------------------------------------------------------------------
#plotting
    
fig = plt.figure(num=1, figsize=(12,8))

ax = fig.add_subplot(211)

xrng = np.arange(-5,-neut_limit,0.01)

ax.plot(xrng,method_u1m(xrng), label = 'Unstable 1')
ax.plot(xrng,method_u2m(xrng), label = 'Unstable 2')
ax.plot(xrng,method_u3m(xrng), label = 'Unstable 3')
ax.plot(xrng,method_u4m(xrng), label = 'Unstable 4')
ax.plot(xrng,method_u5m(xrng), label = 'Unstable 5')
ax.plot(xrng,method_u6m(xrng), label = 'Unstable 6')
ax.plot(xrng,method_u7m(xrng), label = 'Unstable 7')

ax.legend(loc = 'center left', bbox_to_anchor=(1.0,0.5))


ax.set_ylabel('$\psi_m$', fontsize = 15)

ax.tick_params(labelsize = 12)

ax = fig.add_subplot(212)

xrng = np.arange(neut_limit,5,0.01)

ax.plot(xrng,method_s1m(xrng), label = 'Stable 1')
ax.plot(xrng,method_s2m(xrng), label = 'Stable 2')
ax.plot(xrng,method_s3m(xrng), label = 'Stable 3')
ax.plot(xrng,method_s4m(xrng), label = 'Stable 4')

ax.legend(loc = 'center left', bbox_to_anchor=(1.0,0.5))

ax.set_xlabel('z/L', fontsize = 15)

ax.set_ylabel('$\psi_m$', fontsize = 15)

ax.tick_params(labelsize = 12)

plt.tight_layout()

plt.savefig('psym_stab_corr_func.png', dpi = 300, bbox_inches = 'tight')

#------------------------------------------------------------------------------

fig = plt.figure(num=2, figsize=(12,8))

ax = fig.add_subplot(211)

xrng = np.arange(-5,-neut_limit,0.01)

ax.plot(xrng,method_u2h(xrng), label = 'Unstable 2')
ax.plot(xrng,method_u3h(xrng), label = 'Unstable 3')
ax.plot(xrng,method_u4h(xrng), label = 'Unstable 4')
ax.plot(xrng,method_u7h(xrng), label = 'Unstable 7')

ax.legend(loc = 'center left', bbox_to_anchor=(1.0,0.5))


ax.set_ylabel('$\psi_h$', fontsize = 15)

ax.tick_params(labelsize = 12)

ax = fig.add_subplot(212)

xrng = np.arange(neut_limit,5,0.01)

ax.plot(xrng,method_s4h(xrng), label = 'Stable 4')
ax.plot(xrng,method_sdyerh(xrng), label = 'Stable dyer')

ax.legend(loc = 'center left', bbox_to_anchor=(1.0,0.5))

ax.set_xlabel('z/L', fontsize = 15)

ax.set_ylabel('$\psi_h$', fontsize = 15)

ax.tick_params(labelsize = 12)

plt.savefig('psyh_stab_corr_func.png', dpi = 300, bbox_inches = 'tight')`

**Comment by sunt05** [comment]
got it, thanks! @matthew0512l

**Comment by matthew0512l** [comment]
![psym_stab_corr_func_v2](https://user-images.githubusercontent.com/48319587/62777333-1e2ac380-baa5-11e9-90e0-40773eb217c8.png)
Attempt made to correct method 4,

from x = (1 - 19.3*zl_f)**(-0.25) 
to x = (1 - 19.3*zl_f)**(0.25)

**Comment by sunt05** [comment]
Good spot!
Thanks for the correction.
