### ISSUE TITLE
WUProfM_24Hr and WUProfA_24Hr have been defined twice

### ISSUE THREAD

**Issue by zhenkunl** [Urban-Meteorology-Reading/SUEWS#57]
I found `WUProfM_24Hr` and `WUProfA_24Hr` have been defined twice in suews_ctrl_const.f95 under master branch by accident. Since they are in different modules (`allocateArray` and `sues_data`), I assume only one pair of them are actually used.

**Comment by sunt05** [comment]
fixed in https://github.com/Urban-Meteorology-Reading/SUEWS/commit/c7862d2d15ae4e3770fbcdc671ffdd4c775744fa
