### ISSUE TITLE
organisation of the `const` file

### ISSUE THREAD

**Issue by sunt05** [Urban-Meteorology-Reading/SUEWS#58]
As we are enhancing the modularity of code, @zhenkunl and I feel many of the definitions in `suews_ctrl_const.f95` can be reorganised into the respective modules.
It would be good to gather thoughts here on how to improve this.

**Comment by zhenkunl** [comment]
One point I think about is there are too many small modules in this file. Can we untangle them and use structure-type data instead?

**Comment by sunt05** [comment]
Good starting point!
Let's list the todo's here:
- [ ] clean unused modules
- [ ] combine/move small modules

**Comment by sunt05** [comment]
current modules:

- [ ] allocateArray
- [ ] Initial
- [ ] data_in
- [ ] cbl_MODULE
- [ ] snowMod
- [ ] defaultNotUsed
- [ ] time
- [ ] mod_grav
- [ ] mod_k
- [ ] Thresh
- [ ] gas
- [ ] mod_z
- [ ] resist
- [ ] moist
- [ ] gis_data
- [ ] sues_data
- [ ] VegPhenogy
- [ ] filename
- [ ] InitialCond
- [ ] ColNamesModelDailyState
- [ ] ColNamesInputFiles
- [ ] WhereWhen
- [ ] MathConstants
- [ ] PhysConstants

**Comment by sunt05** [comment]
can you suggest the todo's for each of the above modules? @zhenkunl

**Comment by zhenkunl** [comment]
In my opinion, it would be good to have a suitable size and meaningful name for each module. If it it has too many lines,  it becomes less readable. For example, there are many integer-type parameters in `allocateArray`, can we abstract them and create a new module?
