### ISSUE TITLE
Bug in QF_build calculations

### ISSUE THREAD

**Issue by havum** [Urban-Meteorology-Reading/SUEWS#89]
**Describe the bug**
Error in the anthropogenic heat equation calculated using the inventory method. `QF_build` did not include building energy use factor and it followed anthropogenic heat profile. 

**Version and platform (please complete the following information):**
- SUEWS version: 2019a
- linux

**Other remarks**
Possible correction added to `test-dev-QF` branch. I added the needed building energy use and changed the profile from the old anthropogenic heat profile to follow population profile. The anthropogenic heat profile is used preferably only when the inventory method is not used as it should contain components from traffic, human metabolism and buildings. The correction affects QF and also QH values if the inventory method is used.

**Comment by sunt05** [comment]
fixed in #97
