### ISSUE TITLE
Bug in Day of Week cycle

### ISSUE THREAD

**Issue by havum** [Urban-Meteorology-Reading/SUEWS#90]
**Describe the bug**
Error in subroutine Day_Of_Week. The days of the week do not change correctly. I added a figure here to show the difference of weekday (1) /weekend (2) cycle over one year between the different versions of the code. I think that the change can be explained by the added line “DATE = 1” in the v2019 code. Is it needed there or can it be commented away?

![DayofWeek_iu](https://user-images.githubusercontent.com/39586811/67374594-0f26be00-f58a-11e9-821a-71322f18f224.png)

**Version and platform (please complete the following information):**
- SUEWS version: 2019a
- linux

**Comment by sunt05** [comment]
This can certainly be removed/commented out.
I'll fix this soon.
