### ISSUE TITLE
SUEWS MODEL OUTPUT

### ISSUE THREAD

**Issue by khorsans** [Urban-Meteorology-Reading/SUEWS#93]
Hello;
Excuse me I have a question. I ran suews and wrfchem for two dusty days. The incoming and outgoing wavelengths and sensible and latent heat flux of the wrfchem output for dusty days show high values compared to non-dusty days, but the suews model shows low values for dusty days compared to non-dusty days. My question is, which model output is right? I'm really confused.
can you help me?
Thanks and best wishes

**Comment by sunt05** [comment]
Thanks for reaching out to us.
Your question is a bit broad; and given the very limited background information, it is very difficult to justify which model is doing better.
Also, please note: WRF-Chem and SUEWS are very different types of models; an analogy for this would be a fruit box and apple. So arguably they cannot be compared in an easy way.

However, I'm interested to see the following variables for both models:

1. incoming solar radiation;
2. incoming longwave radiation;
3. outgoing solar radiation;
4. outgoing longwave radiation;
5. ground heat flux/storage heat flux;
6. latent heat flux;
and 
7. sensible heat flux.

Also, please clarify:
1. the versions of both models.
2. the configuration info of WRF-Chem.


Thanks,
Ting

**Comment by khorsans** [comment]
thank you so much for your help.
I have run wrf_chem version 3.8 and Suews version standalone 2017b. I used era interim data to run the wrf_chem model and era5 data for the suews model. Of course, I used the solarcalc application for the incoming solar radiation input data to the Suews model. The dates for the dusty days are January 29th  and 30th January .I also sent you the configuration of the model as well as the incoming solar radiation I obtained from the solarcalc program.
Thanks



Sent from Mail for Windows 10

**Comment by khorsans** [comment]
Dear Ting,

Excuse me, I had another question. If I want to use incoming solar radiation data from Era5 as input data to the Suews model, which one data should I download? I took a screenshot of the data and sent it to you. 

thanks

**Comment by sunt05** [comment]
Sorry I didn't see your screenshots: please paste files directly into the GitHub input box here as email attachments might not work.

**Comment by khorsans** [comment]
![Capture](https://user-images.githubusercontent.com/56936152/67434053-33b87f80-f5f6-11e9-99cc-4e9f470423ac.PNG)

**Comment by sunt05** [comment]
surface solar radiation downwards

**Comment by khorsans** [comment]
I sent you the output of the wrfchem model I made with grads software. Colors include:
Blue: downward shortwave flux at ground surface
Green: downward longwave flux at ground surface
Yellow: TOA outgoing longwave
Red color: latent heat flux
Pink: sensible heat flux
 The dust started at 9am and continued until 6pm (local time) and the sky was cloudy for three days before the dust and the day after the dust.
![Capture](https://user-images.githubusercontent.com/56936152/67482981-ad418380-f671-11e9-9883-97aeafe79477.PNG)

I will also send you the output of the suews model text file.
[Ah23_2015_60.txt](https://github.com/Urban-Meteorology-Reading/SUEWS/files/3767322/Ah23_2015_60.txt)

 I used solarcalc software to input incoming solar radiation into the model. This software uses maximum and minimum temperature and rainfall data as input data for incoming shortwave construction and finally provides hourly output according to altitude, lat and lon. It is the lowest for the dusty day (Jan. 2). I checked the era1 data for dusty and non-dusty days and still shows the highest value for dusty days.
However, do I also use era data for incoming shortwave to run the Suews model?
Because in all the articles I read, the incoming solar radiation, the sensible and the latent heat flux are reduced on a dusty day, while the opposite is true for the era۵ and output data of my wrfchem model.

**Comment by sunt05** [comment]
> However, do I also use era data for incoming shortwave to run the Suews model?

Yes.


---
Since your question is more about WRF-Chem, please ask WRF-help for the related questions.

Also your SUEWS version is a bit old, please use 2018c: https://suews-docs.readthedocs.io/en/2018c/

**Comment by khorsans** [comment]
Thank you for your guidance.
I used the 2017b version of the Suews Model because of the boundary layer.
